#!/bin/bash

echo "🚀 DEPLOY RAILWAY - Checklist de Atualização"
echo "=============================================="
echo ""

echo "📋 MUDANÇAS NESTE COMMIT:"
echo "  ✅ Sessão de caixa automática quando agendamento COMPLETED"
echo "  ✅ Campos de endereço separados (street, number, complement, neighborhood)"
echo "  ✅ Migration: 20251119130418_add_salon_address_fields"
echo "  ✅ Remoção da opção 'Suporte' do Sidebar"
echo "  ✅ Correção do bug de desfoco no campo CEP"
echo ""

echo "🗄️  BANCO DE DADOS:"
echo "  ⚠️  Nova migration detectada!"
echo "  📦 Migration: add_salon_address_fields"
echo "  📝 Adiciona campos: street, number, complement, neighborhood ao modelo Salon"
echo ""

echo "🔧 AÇÕES NECESSÁRIAS NO RAILWAY:"
echo ""
echo "1️⃣  ATUALIZAR O CÓDIGO (automático via GitHub):"
echo "   ✅ Railway vai fazer pull do repositório automaticamente"
echo "   ✅ Código já foi commitado e enviado"
echo ""

echo "2️⃣  APLICAR MIGRATIONS (OBRIGATÓRIO):"
echo "   ⚠️  Você DEVE rodar as migrations no Railway!"
echo ""
echo "   Opção A - Via Railway CLI (mais fácil):"
echo "   $ railway run npx prisma migrate deploy"
echo ""
echo "   Opção B - Via Dashboard do Railway:"
echo "   1. Vá em 'Deployments'"
echo "   2. Clique em 'New Deployment'"
echo "   3. Selecione 'Run Custom Command'"
echo "   4. Digite: npx prisma migrate deploy"
echo ""

echo "3️⃣  VERIFICAR VARIÁVEIS DE AMBIENTE (já devem estar ok):"
echo "   ✅ DATABASE_URL (PostgreSQL)"
echo "   ✅ NEXTAUTH_SECRET"
echo "   ✅ NEXTAUTH_URL (https://seu-app.up.railway.app)"
echo "   ✅ NODE_ENV=production"
echo "   ✅ SMTP_* (email - se configurado)"
echo ""

echo "4️⃣  MIGRAR DADOS EXISTENTES (OPCIONAL):"
echo "   Se você tem agendamentos COMPLETED sem sessão de caixa:"
echo ""
echo "   Via Railway CLI:"
echo "   $ railway run node migrate-completed-to-cashier.js"
echo ""
echo "   ⚠️  Isso criará sessões de caixa para agendamentos já concluídos"
echo ""

echo "📊 IMPACTO NO SISTEMA:"
echo "  ✅ Baixo impacto - apenas adiciona colunas novas (nullable)"
echo "  ✅ Dados existentes não serão perdidos"
echo "  ✅ Sistema continua funcionando sem as migrations (mas sem novos recursos)"
echo ""

echo "🧪 TESTAR APÓS DEPLOY:"
echo "  1. Login no dashboard"
echo "  2. Ir em 'Meu Salão' - verificar se campos de endereço aparecem"
echo "  3. Ir em 'Agendamentos' - marcar um como 'Concluído'"
echo "  4. Ir em 'Caixa' - verificar se aparece sessão aberta"
echo ""

echo "🔗 LINKS ÚTEIS:"
echo "  Railway Dashboard: https://railway.app/dashboard"
echo "  Docs Prisma: https://www.prisma.io/docs/guides/migrate/production-migrations"
echo ""

echo "✅ RESUMO:"
echo "  - Código: ✅ Já no GitHub"
echo "  - Railway: ⚠️  Precisa rodar 'prisma migrate deploy'"
echo "  - .env: ✅ Sem novas variáveis necessárias"
echo ""

echo "💡 COMANDO RÁPIDO PARA DEPLOY COMPLETO:"
echo "   $ railway run npx prisma migrate deploy && railway up"
echo ""
