#!/bin/bash

echo "🧪 Testando API de Usuários..."
echo ""
echo "Problema: Lista de usuários não atualiza após criar/editar"
echo "Solução aplicada:"
echo "  1. ✅ API agora retorna { users: [...] } ao invés de array direto"
echo "  2. ✅ Adicionado cache: 'no-store' no fetch para forçar dados frescos"
echo "  3. ✅ Adicionado router.refresh() após salvar"
echo "  4. ✅ Adicionado listener window 'focus' para recarregar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Como testar:"
echo ""
echo "1. Acesse: http://localhost:3000/dashboard/usuarios"
echo "2. Clique em 'Novo Usuário'"
echo "3. Preencha o formulário e salve"
echo "4. Verifique se a lista atualiza automaticamente"
echo ""
echo "Se ainda não funcionar:"
echo "  - Abra o DevTools (F12)"
echo "  - Vá em Console"
echo "  - Procure por erros em vermelho"
echo "  - Verifique a aba Network para ver a resposta da API"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Verificando servidor Next.js..."

if pgrep -f "next dev" > /dev/null; then
    echo "✅ Servidor Next.js está rodando na porta 3000"
    echo ""
    echo "⚠️  IMPORTANTE: O Next.js usa cache agressivo!"
    echo "   Para ver as mudanças, faça:"
    echo "   1. Recarregue a página com Ctrl+Shift+R (hard reload)"
    echo "   2. Ou feche e abra o navegador novamente"
    echo ""
else
    echo "❌ Servidor Next.js não está rodando!"
    echo "   Execute: npm run dev"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Usuários atualmente no banco:"
echo ""

node check-users.js | grep -A 20 "LISTA DE USUÁRIOS"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Correção aplicada com sucesso!"
echo ""
